### ISSUE TITLE
Homepage Prototype

### ISSUE THREAD

**Issue by MohmmadAlharran** [Albrenik/recipes-homecooking#3]
here is the link to prototype of the homepage.
https://mockittapp.wondershare.com/app/33454a2777925322df8afa92ddcca99750d13149?simulator_type=device&sticky
If we need to change anything, let us know.

**Comment by Albrenik** [comment]
The Blue base color is too intensive make it warmer and not so strong. so the user is overwhelmed by the color. Also please add a light grey background as told in the description. The accent color is also not as nicely as we would like it. So pls change the colors.

**Comment by shresdee** [comment]
Dear MohmmadAlharran,
Also consider the logo subtle; consider using different color such as white hat and different friendly colors for fork and spoon. The logo and overall color doesn't look appealing.
Thank you and warm regards.

**Comment by MohmmadAlharran** [comment]
i have just uploaded the new lodge .please have a look at it.

**Comment by MohmmadAlharran** [comment]
i have just uploaded the new Logo .please have a look at it

**Comment by Albrenik** [comment]
The Logo looks fine but pls remove the single white spot in the middle of the face. Its distracting so pls remove it than i think the logo is done.

**Comment by MohmmadAlharran** [comment]
will do!
